### ISSUE TITLE
Unsafe JavaScript attempt to access frame with URL about:blank from frame with URL file:///Users/Shared/Dropbox/Sites/website.com/node_modules/grunt-grunticon/node_modules/svg-to-png/lib/phantomscript.js. Domains, protocols and ports must match.

### ISSUE THREAD

**Issue by pryley** [filamentgroup/grunticon#205]
At first I thought this error was responsible for grunticon not completing. However, after a little digging I found the culprit and opened Issue #206

It would still be nice to not see this notice/error. :)
```
Running "grunticon:svg" (grunticon) task
Look, it's a grunt icon!  
grunticon now minifying the stylesheet loader source.  
grunticon loader file created.  
Coloring SVG files  
Converting SVG to PNG  
svg-to-png now spawning phantomjs...  
(using path: /Users/Shared/Dropbox/Sites/website.com/node_modules/grunt-grunticon/node_modules/svg-to-png/node_modules/phantomjs/lib/phantom/bin/phantomjs)  
Unsafe JavaScript attempt to access frame with URL about:blank from frame with URL file:///Users/Shared/Dropbox/Sites/website.com/node_modules/grunt-grunticon/node_modules/svg-to-png/lib/phantomscript.js. Domains, protocols and ports must match.
```

I tried adding `"--web-security=false"` to `node_modules/grunt-grunticon/node_modules/svg-to-png/lib/svg-to-png.js` but it didn't seem to change anything.
```
execFile( phantomJsPath,
	[
		"--web-security=false",
		phantomfile,
		input,
		output,
		opts.pngfolder,
		opts.defaultWidth,
		opts.defaultHeight
	],
...
```

**Comment by jefflembeck** [comment]
Unfortunately, this is a PhantomJS issue that we can't get around - https://github.com/ariya/phantomjs/issues/12697

**Comment by linehammer** [comment]
Crossframe-Scripting is not possible when the two frames have different domains -> Security. This means that [youtube](http://net-informations.com/q/mis/youtube.html) is trying to reach out to the caller frame for some reason and it's disabled because it would be a cross-domain call.

The better solution is to change the iframe.src to a url on the same domain, but which was actually an html re-direct page to the desired domain. The other domain then showed up in your iframe without any errors.

Another solution could be to use a local file which retrieves the remote content.
