### ISSUE TITLE
Embedding doesn't work with CDN?

### ISSUE THREAD

**Issue by crohrer** [filamentgroup/grunticon#217]
I use a CDN for delivering all my assets (including the grunticon CSS). 
Embedding doesn't work on my stage-Server with CDN (while it works perfectly locally without CDN). 
I get the following JS-Error:
`Uncaught TypeError: Cannot read property 'length' of null`

**Comment by scottjehl** [comment]
Hmm. Yeah okay that makes sense. It won't be able to access those CSS rules on externally-hosted CSS without CORs enabled, per my understanding at least.

It sounds like as of HTML5, you can set a `crossorigin` attribute on the `link`, and that'll work as long as the CDN has CORs enabled for your domain. Do you happen to have access to enable that to test it out?

**Comment by jimlakey** [comment]
I'm having the same issue with Shopify, which uses a CDN for all assets. The grunticon 1.x functionality works just fine, but I get the same JS error as @crohrer for embedding.

@scottjehl — I am using the following to initiate grunticon. Since there isn't a link tag in use here, is there any way of using the `crossorigin` attribute that you mentioned? Thank you!

```
grunticon( ['{{ "icons.data.svg.css" | asset_url }}', '{{ "icons.data.png.css" | asset_url }}', '{{ "icons.fallback.css" | asset_url }}'], function(){
  grunticon.ready(function(){
    grunticon.embedIcons(grunticon.getIcons(grunticon.href));
    //https://github.com/filamentgroup/grunticon/issues/213
    TweenMax.staggerTo($(".star"), 1.2, {
      scale: 0.5,
      fill: "#C8BDE5",
      repeat: -1,
      yoyo: true,
      transformOrigin:"50% 50%"
    }, 0.25);
  });
});
```

**Comment by scottjehl** [comment]
Hi again
I’ve got a small JS change working locally now that we may consider offering as a x-domain extension. 

The main idea is that the CSS will need to be requested via Ajax because the `link[crossorigin]` attribute does not appear to work in Chrome (works in other browsers though).

The ajax patch seems to work well across browsers. It’d still require that the remote server has CORs enabled however.

I should have something up shortly that you can test.

Thanks
Scott

**Comment by scottjehl** [comment]
Hey @crohrer and @jimlakey,

Okay! I've got something for you to try out, and it'd be really helpful to know if it's working for you.

I've been working in the `cors-ext` branch if you're interested in the code, but basically I added a couple of methods to the loader that facilitate x-domain CSS loading with ajax instead of a link element. We're discussing whether to include these in the loader whenever the svg embed option is set, or when an additional cross-domain option is set. 

In the meantime, if you could test out this new loader and see whether it helps, that'd be great.

Here's the loader JS minified, which is a combination of [this loader.js file](https://github.com/filamentgroup/grunticon/blob/cors-ext/tasks/grunticon/static/grunticon.loader.js) and [this loader svg embed extension](https://github.com/filamentgroup/grunticon/blob/cors-ext/tasks/grunticon/static/grunticon.embed.js):

``` js
/*! grunt-grunticon Stylesheet Loader - v2.0.2 | https://github.com/filamentgroup/grunticon | (c) 2015 Scott Jehl, Filament Group, Inc. | MIT license. */
(function(e){function t(t,n,r,o){"use strict";function a(){for(var e,n=0;u.length>n;n++)u[n].href&&u[n].href.indexOf(t)>-1&&(e=!0);e?i.media=r||"all":setTimeout(a)}var i=e.document.createElement("link"),c=n||e.document.getElementsByTagName("script")[0],u=e.document.styleSheets;return i.rel="stylesheet",i.href=t,i.media="only x",i.onload=o||function(){},c.parentNode.insertBefore(i,c),a(),i}var n=function(r,o){"use strict";if(r&&3===r.length){var a=e.navigator,i=e.Image,c=!(!document.createElementNS||!document.createElementNS("http://www.w3.org/2000/svg","svg").createSVGRect||!document.implementation.hasFeature("http://www.w3.org/TR/SVG11/feature#Image","1.1")||e.opera&&-1===a.userAgent.indexOf("Chrome")||-1!==a.userAgent.indexOf("Series40")),u=new i;u.onerror=function(){n.method="png",n.href=r[2],t(r[2])},u.onload=function(){var e=1===u.width&&1===u.height,a=r[e&&c?0:e?1:2];n.method=e&&c?"svg":e?"datapng":"png",n.href=a,t(a,null,null,o)},u.src="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///ywAAAAAAQABAAACAUwAOw==",document.documentElement.className+=" grunticon"}};n.loadCSS=t,e.grunticon=n})(this);(function(e,t){"use strict";var n=t.document,r="grunticon:",o=function(e){if(n.attachEvent?"complete"===n.readyState:"loading"!==n.readyState)e();else{var t=!1;n.addEventListener("readystatechange",function(){t||(t=!0,e())},!1)}},a=function(){return t.document.querySelector('link[href$="'+e.href+'"]')},i=function(e){var t,n,o,i,c,u,s={};if(e||(e=a()),t=e&&e.sheet,!t)return s;n=t.cssRules?t.cssRules:t.rules;for(var l=0;n.length>l;l++)o=n[l].cssText,i=r+n[l].selectorText,c=o.split(");")[0].match(/US\-ASCII\,([^"']+)/),c&&c[1]&&(u=decodeURIComponent(c[1]),s[i]=u);return s},c=function(e){var t,o,a;o="data-grunticon-embed";for(var i in e)if(a=i.slice(r.length),t=n.querySelectorAll(a+"["+o+"]"),t.length)for(var c=0;t.length>c;c++)t[c].innerHTML=e[i],t[c].style.backgroundImage="none",t[c].removeAttribute(o);return t},u=function(){"svg"===e.method&&o(function(){c(i())})},s=function(e){var n=new t.XMLHttpRequest;return"withCredentials"in n?n.open("GET",e,!0):t.XDomainRequest!==void 0?(n=new t.XDomainRequest,n.open("GET",e)):n=null,n},l=function(){"svg"===e.method&&o(function(){var t=s(e.href);t&&(t.onload=function(){var r=n.createElement("style");r.innerHTML=t.responseText;var o=e.getSVGCSS();o.parentNode.insertBefore(r,o),o.parentNode.removeChild(o),c(i(r))},t.send())})};e.embedIcons=c,e.getSVGCSS=a,e.getIcons=i,e.ready=o,e.ajaxGet=s,e.svgLoadedCallback=u,e.svgLoadedCORSCallback=l})(grunticon,this);
```

If you replace your loader with that, it'll expose a new `grunticon.svgLoadedCORSCallback` method, which is what you'll want to use instead of the `grunticon.svgLoadedCallback` method that only worked with same-domain CSS.

With that edit, your call to grunticon will look something like this:

`grunticon(["http://example.com/icons.data.svg.css", "http://example.com/icons.data.png.css", "http://example.com/icons.fallback.css"], grunticon.svgLoadedCORSCallback );`

And as noted above, that remote server will need CORS enabled. Here's how that looks in htaccess, as one example:

```
<IfModule mod_headers.c>
    Header add Access-Control-Allow-Origin "*"
</IfModule>
```

Works for me on a couple domains, but please let me know how you fair!

Thanks

**Comment by jimlakey** [comment]
Yes, thank you! It works perfectly now with Shopify, so I guess they have CORS enabled on their CDN. I had to make a few changes in order to call the GSAP animation on the embedded SVG which I'll add below in case it's of help to anyone else down the line. Thank you, @scottjehl. I love the fact that I have clients who are paying me for my services and will take days to get back to me, yet the two times I've posted an issue on this repo, you guys are on it straight away. Thank you so much! 

```
grunticon( ['{{ "icons.data.svg.css" | asset_url }}', '{{ "icons.data.png.css" | asset_url }}', '{{ "icons.fallback.css" | asset_url }}'], function(){
  grunticon.ready(function(){
    var xhr = grunticon.ajaxGet( grunticon.href );
    if ( !xhr ){ return; }
    xhr.onload = function() {
      var style = document.createElement( "style" );
      style.innerHTML = xhr.responseText;
      var ref = grunticon.getSVGCSS();
      ref.parentNode.insertBefore( style, ref );
      ref.parentNode.removeChild( ref );
      grunticon.embedIcons( grunticon.getIcons( style ) );
      // adding GSAP animation call for SVG just embedded
      TweenMax.staggerTo('.star', 1.2, {
        scale: 0.5,
        fill: "#C8BDE5",
        repeat: -1,
        yoyo: true,
        transformOrigin:"50% 50%"
      }, 0.25);
    };
    xhr.send();
  });
});
```

**Comment by scottjehl** [comment]
Great to hear.
And yes, that's useful to know. Sounds like you could use a callback or event when the embed markup is ready?

(Thanks for the kind words. @jefflembeck is the one who's usually on top of all the issues here :) )

**Comment by jimlakey** [comment]
Yes, a callback for when the embed markup is ready would be awesome. Thanks!

**Comment by jefflembeck** [comment]
Adding this - https://github.com/filamentgroup/grunticon/issues/219 - will put it in after this is closed

**Comment by scottjehl** [comment]
Closing out. Both this and the callback are in master now. V 2.1

**Comment by sbay** [comment]
I am having a similar issue as the origin poster, but my problem is not with loading the CSS, but with embedding via "getIcons" method. I pinned the issue to loaded and created CSSStyleSheet not populating either "cssRules" or "rules" objects, resulting in getIcons getting a "Cannot read property 'length' of null". Any thoughts on how to resolve this? Thanks.
