### ISSUE TITLE
grunticon loader api: throw appropriate errors for undefined args

### ISSUE THREAD

**Issue by scottjehl** [filamentgroup/grunticon#221]
Keep size in mind - this js is inlined

**Comment by zachleat** [comment]
This repository is now using [lodash style issue management](https://twitter.com/samselikoff/status/991395669016436736) for enhancements. This means enhancement issues will now be closed instead of leaving them open.

View [the enhancement backlog here](https://github.com/filamentgroup/grunticon/issues?utf8=%E2%9C%93&q=label%3Aneeds-votes+sort%3Areactions-%2B1-desc+). Don’t forget to upvote the top comment with 👍!
