### ISSUE TITLE
Sass/SCSS Implementation

### ISSUE THREAD

**Issue by johnny5th** [filamentgroup/grunticon#232]
Is there any plan to implement Sass or SCSS in the output? I'm looking to replace my Sass sprites stack with an SVG system, and a close-to-drop-in replacement would be sick!

**Comment by jefflembeck** [comment]
@johnny5th we output in css, but that doesn't mean you can't output the
```
datasvgcss
datapngcss
urlpngcss
```
options to a scss file.

Example:

In our [Gruntfile, we have](https://github.com/filamentgroup/grunticon/blob/master/Gruntfile.js#L46) -

```
datasvgcss: "icons.data.svg.css",
datapngcss: "icons.data.png.css",
urlpngcss: "icons.fallback.css",
```

you could very easily make that:

```
datasvgcss: "icons.data.svg.scss",
datapngcss: "icons.data.png.scss",
urlpngcss: "icons.fallback.scss",
```

to make it into three sass files, since scss is a superset of css.
