### ISSUE TITLE
Option to disable png icons

### ISSUE THREAD

**Issue by herkyl** [filamentgroup/grunticon#243]
It would be nice if there was an option to disable png icons so Phantomjs wont get run every time.

**Comment by jefflembeck** [comment]
Since grunticon is meant to be an all-around solution for providing css for icons with fallbacks, it's not within the scope of the project to disable png icons.

However, it DOES use [Directory-Encoder](https://github.com/filamentgroup/directory-encoder) to generate the CSS files that you're looking for. I strongly recommend using that instead if that's all you want.

Thanks!

**Comment by wytrych** [comment]
I would backup this request. Our project doesn't need to support PNGs and having a flag to not generate them would be very useful and speed up our CI a lot. It doesn't mean the project would stop being an all-round solution - having the option of generating PNGs would still be there.

**Comment by dominikwilkowski** [comment]
Why not just deleting the request for the PNG fallback? It's pretty easy to limit your implementation of what grunticon generates to just what you need. You could even just delete the `symbols.fallback.css` file and replace it in your embed script with `symbols.data.png.css`... for a lack of a quicker hack no?

```html
<script>
	grunticon([
			"assets/css/symbols.data.svg.css",
			"assets/css/symbols.data.png.css",
			"assets/css/symbols.data.png.css"
		],
		grunticon.svgLoadedCallback
	);
</script>
<noscript><link href="assets/css/symbols.data.png.css" rel="stylesheet"></noscript>
```
