### ISSUE TITLE
Embed SVG into appended content with CDN stylesheet

### ISSUE THREAD

**Issue by dcalhoun** [filamentgroup/grunticon#250]
If my Grunticon produced stylesheet is served from a CDN, is it possible to embed SVG elements into DOM elements that have been appended via JavaScript? This is basically a combination of #217 and #212.

It is not working for me currently. The SVG's are successfully embedded the _first_ time I call `grunticon.svgLoadedCORSCallback()`, but are not in an later calls. In other words, the first time my Backbone view renders, the icons are embedded. Any additional times the view is rendered, the icons are not successfully embedded. There are no console errors.
### Grunticon config

``` coffeescript
grunticon:
  project:
    files: [
      expand: true,
      cwd: "app/assets/images/icons"
      src: ["**/*.svg", "**/*.png"]
      dest: "app/assets/stylesheets/base/icons"
    ]
    options:
      enhanceSVG: true
      corsEmbed: true
```
### Load Grunticon

``` html
<script>/* [grunticon-loader] */</script>
<script>
grunticon([
    "http://cdn.com/icons.data.svg.css",
    "http://cdn.com/icons.data.png.css",
    "http://cdn.com/icons.fallback.css"
]);
</script>
```
### Embed SVG

This is called each time the Backbone view is rendered.

``` javascript
// After Backbone view rendered...
grunticon.svgLoadedCORSCallback(); 
```
### Network Requests

Seen below, the initial stylesheet request (on page load) and each additional request from the Backbone view being rendered. The first rendering successfully embeds the icons (second request), the second rendering fails to embed (third request).

![grunticon cors ajax](https://cloud.githubusercontent.com/assets/438664/6672990/ebe20812-cbdd-11e4-91f1-fcd6b06084e4.png)

**Comment by dcalhoun** [comment]
Actually, there was a console an error.

![grunticon console error](https://cloud.githubusercontent.com/assets/438664/6673947/8b8d6338-cbe4-11e4-8878-85bd61dd816f.png)

**Comment by dcalhoun** [comment]
After digging further, the `ref` variables found in the [svgLoadedCORSCallback](https://github.com/filamentgroup/grunticon/blob/v2.1.6/tasks/grunticon/static/grunticon.embed.cors.js#L30) appears to be returning as `null` for each additional request.

Apologies for the variables in this screen shot, but I merely unminified the loader script that Grunticon generates. The first `o` and `r` are from the initial rendering of the Backbone View. The second set are from when I revisited the view.

![grunticon-cors-embed](https://cloud.githubusercontent.com/assets/438664/6782924/f359ce60-d144-11e4-8a59-5e906d19e6f9.png)

I believe the `r` is the `ref` variable. Should this `ref` variable be `null` after the first time I call `grunticon.svgLoadedCORSCallback()`?

**Comment by jefflembeck** [comment]
I think the culprit is here: https://github.com/filamentgroup/grunticon/blob/master/tasks/grunticon/static/grunticon.embed.js#L77 - when we embed icons, we remove the attribute that says "embed icons here" at that point. We originally did this for performance reasons and, mostly, because we hadn't thought that people would use Grunticon to re-embed multiple times over.

If there's any way to avoid re-embedding, that would likely be beneficial for you, but I'm looking into other options.

**Comment by dcalhoun** [comment]
I'm not sure if the removal of the attribute is the culprit. The Backbone view template is removed and re-added to the DOM. So, the `data-grunticon-embed` is on the element for any additional embed calls.

For the time being I've stopped using my CDN and CORS. I'm serving the icon stylesheets from the local server.

**Comment by jefflembeck** [comment]
So this is ONLY happening with repeat views when using the CORS setup?

**Comment by dcalhoun** [comment]
Yes, the initial rendering of the Backbone view successfully embeds the SVG icons. Subsequent renderings of the view *fail* to embed the SVG icons. Since this only happens when using CORS, I figured it had something do with the additional requests for the same stylesheet.

**Comment by jefflembeck** [comment]
Ah,

Then yes - https://github.com/filamentgroup/grunticon/blob/master/tasks/grunticon/static/grunticon.embed.cors.js#L33

So, in order to make CORS work, we take the stylesheet, and then embed it into the `head`. We then remove the stylesheet (to prevent conflicts, mostly) - this is once again, a case where we didn't intend on this being called multiple times. I'll see what I can do to further decouple the rendering part.
