### ISSUE TITLE
SVG embedding across domains fails intermittently

### ISSUE THREAD

**Issue by ambienttraffic** [filamentgroup/grunticon#279]
Thanks for making grunticon! It's been super handy. So I'm trying to use the data-grunticon-embed attribute and svgLoadedCORSCallback but this error occurs about 80% of the time on page load in some browsers:

"XMLHttpRequest cannot load http://static.staging-seriouseats.com/1/braestar/staging/icons/icons.data.svg.css. Origin http://www.staging-seriouseats.com is not allowed by Access-Control-Allow-Origin."

Here's the CORS policy we're using:

```
<?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
 <CORSRule>
        <AllowedOrigin>http://staging-seriouseats.com</AllowedOrigin>
        <AllowedOrigin>http://www.staging-seriouseats.com</AllowedOrigin>
        <AllowedOrigin>http://*.staging-seriouseats.com</AllowedOrigin>
        <AllowedMethod>GET</AllowedMethod>
        <MaxAgeSeconds>3000</MaxAgeSeconds>
        <AllowedHeader>Authorization</AllowedHeader>
        <AllowedHeader>x-requested-with</AllowedHeader>
        <AllowedHeader>Origin</AllowedHeader>
    </CORSRule>
</CORSConfiguration>
```

I've created a stripped down test page that exhibits this issue:
http://www.staging-seriouseats.com/icon-test

I'm seeing this behavior in recent versions of iOS and desktop Safari. Chrome and IE 11 display the icons reliably with no error.

An example of the icons loading correctly and the Resources list in Safari's console:
![correct-load](https://cloud.githubusercontent.com/assets/71891/8727995/cc44fe28-2bb0-11e5-8c2f-25aa8749c58e.png)

An example of the icons loading incorrectly and the Resources list in Safari's console (notice three refs to icons.data.svg.css, one of them is red):
![incorrect-load](https://cloud.githubusercontent.com/assets/71891/8728014/e99f3236-2bb0-11e5-9d00-503f63553a63.png)

**Comment by rvitre** [comment]
Same problem here. Amazon doesn't seems to handle CORS configuration the way we're expecting to.

I've tried to put my svg.css on a php server with the following code inside my .htaccess :
```
<IfModule mod_headers.c>
    Header add Access-Control-Allow-Origin stage.mywebsite.com
</IfModule>
```
It worked.
However, using Amazon S3 is a top priority for me.

Any workaround ?

**Comment by rvitre** [comment]
Just found a solution. I can't explain exactly why it works, but the fact is that Safari is using an older webkit version than the last version of Chrome. This webkit version totally mess things up with the headers sent by Amazon S3. (Vary header, likely)

It means that older Chrome versions (v23 or so) will have the same issue.

To make grunticons script works on Safari with CORS enabled, I've added the following header to the AJAX request :
```
If-None-Match: webkit-no-cache
```
Which in JS would be : 
```
request.setRequestHeader("If-None-Match", "webkit-no-cache");
```

Any feedback from filamentgroup would be appreciated !

**Comment by danigirl329** [comment]
I also had this issue. @rvitre's solution worked for me as well.

**Comment by jaydiablo** [comment]
From our testing, I believe that the reason this fails from an S3 (or CloudFront) CDN is because S3 doesn't send the `Access-Control-Allow-Origin` header to requests that don't have the `Origin` header.  It seems that Chrome/Safari are caching the normal HTTP request for the `icons.data.svg.css` (and the headers that came back with it, that don't include `Access-Control-Allow-Origin` header) so when the XHR request is set to be made, the browser just returns the cached version of the request, which causes the XHR to fail since the `Access-Control-Allow-Origin` header isn't present.

@rvitre's fix with the `webkit-no-cache` header must tell the browser not to use the cache for that XHR request, sending a new request to S3/CloudFront with the `Origin` header in place, which will have the `Access-Control-Allow-Origin` header in the response.

Another possible solution, which we haven't had a chance to test just yet is to add a `crossorigin="anonymous"` attribute to the CSS's link element that grunticon inserts into the document.  This should cause the browser to send the `Origin` header with the request.

**Comment by jaydiablo** [comment]
I've confirmed that modifying the cssLoader and adding `crossorigin="anonymous"` to the injected link tags does fix this for Chrome (causes chrome to send the `Origin` header with the initial stylesheet request) but Safari doesn't seem to obey that attribute on a link tag (as of this writing).

It seems reasonable that this attribute be added to any grunticon injected link tags, but would probably be nice to only enable that when it's a CORS embed.  Looking through the projects required to make this happen probably requires changes/coordination between this project, the grunticon lib projects and the css loader project.

That said, I don't know the implications of adding this attribute willy-nilly (other than that it adds the Origin header to the request), i.e., will the browser reject the loading of the CSS if the server that serves the CSS doesn't send back an `Access-Control-Allow-Origin` header?
