### ISSUE TITLE
data-grunticon-embed and <button> element

### ISSUE THREAD

**Issue by extractachris** [filamentgroup/grunticon#290]
I am using the `data-grunticon-embed` attribute on a `button` element to embed a standard hamburger menu svg:

```
<button class="header__menu-toggle  icon-hamburger-menu  js-toggle-nav" data-grunticon-embed>Open Menu</button>
```

In mobile Safari on iOS 8.4 and Safari 8.0.8 on OSX, the hamburger menu gets cropped, displaying only 2 of its 3 bars. But on all other browsers the hamburger menu displays fully.

If I swap the `button` element out for a `span`, the problem disappears. So something to do with `button` and Safari. Any ideas?

**Comment by benjgorman** [comment]
Have you tried styling the SVG inside the button directly? I had a similar issue, except my SVGs were too large and breaking out of their div boxes.

So on my page I have something like this:

```
<div id="logo_nav" class="icon-bg" style="background-image: none;">
    <!--?xml version="1.0" encoding="UTF-8" standalone="no"?-->
       <svg width="44px" height="44px" viewBox="0 0 44 44" version="1.1"      xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:sketch="http://www.bohemiancoding.com/sketch/ns">
       </svg>
</div>
```

The class icon-bg is unchanged from the grunticon CSS. But logo_nav has something like:

#logo_nav svg {
width:50px;
height:50px;
}

So this scales the SVG without messing anything else up. Seems to work in all browsers. I have a few on my page here where you can play with the css yourself http://benjgorman.com/

I'm not sure if this is the best approach, but otherwise I had similar issues.

**Comment by extractachris** [comment]
Strange, so this works:

```
<button>
    <svg xmlns="http://www.w3.org/2000/svg" class="header__menu-toggle  icon  icon-hamburger-menu  js-toggle-nav">
        Open Menu
    </svg>
</button>
```

But not:

```
<button class="header__menu-toggle  icon-hamburger-menu  js-toggle-nav" data-grunticon-embed>
    Open Menu
</button>
