### ISSUE TITLE
Generated png files contain svg source rather than the generated image

### ISSUE THREAD

**Issue by jtbr** [filamentgroup/grunticon#292]
This is really a problem with svg2min, but the current suggested usage for grunticon, combining svgmin with grunticon will result in this problem at least on Windows 7.

See: https://github.com/dbushell/grunt-svg2png/issues/12

The workaround is to use an optional parameter to disable svgmin's removal of the XML declaration in the SVG files:

```
svgmin: {
    dist: {
        options: {
            plugins: [
                { removeXMLProcInst: false } // don't remove xml processing instructions (doing so causes svg2png to fail at least on win 7)
            ]
        },
        files: [{
            expand: true, cwd: 'sourcedir', src: ['*.svg'], dest: 'destdir'
        }]
    }
}
```

It might be worth updating the documentation with this workaround. Alternatively, so long as svg2png isn't going to fix this (and it was reported a year and half ago), grumticon could minify svgs after converting them to png, allowing the best of both worlds (correct pngs as well as optimally minfied svgs).

**Comment by jefflembeck** [comment]
Yeah, this definitely has been an issue that has been flagged several times and that we've ended up telling people about the fix each time. This should definitely be a documentation update (if you have suggestions as to where, I'd love to take a PR for it -- documentation is difficult to lay out when you're really engrossed in the internals of a project, so any outside contribution in this manner is REALLY appreciated).

On the code note: svg2png isn't a library that we use (we use svg-to-png, which their plugin doesn't use either), and even if it was, svg-to-png is a module that, at its core, takes a screen shot of how the OS renders the SVG (via phantomjs). Since Windows has an issue with rendering SVGs if they do not have the XML designation at the top, this can be a problem if it's stripped out by a minifier, or the user themselves.

Grunticon is a wrapper for https://github.com/filamentgroup/grunticon-lib, and I'd prefer to keep away from increasing its dependencies. Since svgmin is completely optional, it's just a suggestion at this point and is not part of our library -- and given that we've seen it break on some weird edge cases in the past, outside of this windows issue, I'd like to keep it a suggestion as it's just not in the scope of what we can fix/work on.

**Comment by jtbr** [comment]
Didn't realize the image was rendered by the OS. I went ahead and made a PR for the readme for this. 

Thanks for your great work.
