### ISSUE TITLE
Grunticon has no files to read

### ISSUE THREAD

**Issue by sd-92** [filamentgroup/grunticon#306]
Hi there,

I am trying to run gulpicon after I generate my optimised svgs using svg-min like so:

`gulp.task("icons",['optimise_svgs'], gulpicon(glob.sync(paths.icons.src), gulpiconConfig));`

However the first time that I run the "icons" task I get:

`[12:00:50] Look, it's a gulpicon!
[12:00:50] Grunticon has no files to read!`

If I run the task again, it works just fine. Is there a reason for this?

**Comment by ginnsquad** [comment]
I have been having this problem as well and have tried to upgrade to Gulp 4 to see if `gulp.series` would fix the issue. Same problem. 

I tried using `gulp-svgo` instead of `gulp-svgmin`, but it still doesn't see the SVGs on the first run.

I tried adding a timeout function to test if the gulpicon task was somehow starting before the `gulp-svgo` task was finished, but it makes no difference.

**Comment by ginnsquad** [comment]
@simonedeluca I actually had to completely bail on the `gulp-gulpicon` plugin and use `grunticon-lib` instead. Here is a link to the related post that I implemented:
https://gist.github.com/dcalhoun/e79ad10d518612d70721#gistcomment-1770627
