### ISSUE TITLE
Can I embed SVGs without loading fallbacks?

### ISSUE THREAD

**Issue by giofilo** [filamentgroup/grunticon#333]
Hi all,

Is there a way to use grunticon only to embed SVGs without loading the PNG and CSS fallback files?

If not, can you suggest me a different script/plugin (as good as grunticon 👍 )  that does what I need?

Thank you!

**Comment by vorbe** [comment]
You could try [svg-sprite](https://github.com/jkphl/svg-sprite), it inlines sprites using the <defs> or <symbol> element but you're probably going to need some sort of polyfill like svgxuse if you're planning on supporting IE9+ and you don't want to deal with png or css fallbacks.

**Comment by kemalkolayca** [comment]
Yes you can. I wanted the same thing because my project targeted IE9+ and there was no need to load fallbacks.

` grunticon: {
      myIcons: {
        files: [{
            expand: true,
            cwd: 'svg',
            src: ['*.svg', '*.png'],
            dest: 'css_target_dir'
          }],
        options: {
          datasvgcss: "style.svg.css",
        }
      }
    }`

Lets say your main css file name for the whole site is style.css (resides in css_target_dir). The trick is this: When you run grunt grunticon with the options above it will output style.svg.css file to the same directory with style.css. Use grunt-contrib-cssmin grunt task and when you run `grunt cssmin` that will combine style.css and style.svg.css into style.min.css ( since they start with the same prefix 'style' ). Then you can load just one css file and forget about fallbacks and grunticon javascript file.

Wish this will help.
