### ISSUE TITLE
ReferenceError: primordials is not defined

### ISSUE THREAD

**Issue by stratboy** [filamentgroup/grunticon#347]
> Currently on osx 10146, grunticon 232, node 12141.

When I launch the grunt command on a grunticon folder, I keep getting ReferenceError: primordials is not defined. Also 

> Warning: Task "grunticon:icons" not found. Use --force to continue.

how to solve?

**Comment by lukebooroo** [comment]
Also getting the same issue, seems to be on Node versions 12+

**Comment by stratboy** [comment]
Seems devs doesn't look here too much :)

**Comment by lukebooroo** [comment]
Anyone happen to know a good alternative? Hopefully one that I could migrate easily to 😂

**Comment by rulrok** [comment]
I found this [SO answer](https://stackoverflow.com/questions/55921442/how-to-fix-referenceerror-primordials-is-not-defined-in-node)

> I hit the same error. I suspect you're using node 12 and gulp 3. That combination does not work: https://github.com/gulpjs/gulp/issues/2324
> 
> A previous workaround from Jan. does not work either: https://github.com/gulpjs/gulp/issues/2246
> 
> Solution: Either upgrade to gulp 4 or downgrade to an earlier node.

**Comment by stratboy** [comment]
So gulp and not grunt?

**Comment by rulrok** [comment]
@stratboy  Oh, the same happend for me with grunt and the fixes worked as well. :+1:

**Comment by troylutton** [comment]
Guys we had the same problem and we used the same workaround that @rulrok mentioned.  This works with NPM and shrinkwrap.  Alternatively a node downgrade to < v12 also works.

The problem for us is that we use Yarn w/workspaces and Monorepos and the only real solution was to go back to a version of node < 12 or use NPM instead of yarn.  We'd prefer to use all the new shiny things and we'd love to see grunticon keep on being a first class member of the grunt world.

If the team here at could (pretty please) just update their dependencies so that they're compatible with Node >= 12 then that would be completely awesome and it would give life to Grunticon for many years. @zachleat @scottjehl @toddparker

**Comment by scottjehl** [comment]
Hi! This seems fine and reasonable. I'll set a reminder to take a look in the morning. 

That aside, we need to give this pattern/project a look for moving forward. In our projects, we're typically embedding SVG directly or externally from sprites or direct files now and not necessarily using workflows to generate fallback images since svg browser support is very good. 

This project, while still not totally ready for distribution, has been a decent alternative for us recently https://github.com/filamentgroup/iconoclash

**Comment by troylutton** [comment]
thank you @scottjehl  that would be great!

**Comment by scottjehl** [comment]
@troylutton happy to fix it up. Could you help clarify for me the extent of the change? I'd like to get a PR to test and I'm seeing some notes about gulp, which shouldn't be a dependency for this... Just want to get the change right. thanks!

**Comment by khateeb321** [comment]
@rulrok fix worked for me!

**Comment by Muffinman** [comment]
Just had this myself with an old legacy project. For me the fix was from the same StackOverflow post but the newer npm syntax:

```json
{
  // Your current package.json
  "overrides": {
    "graceful-fs": "^4.2.9"
  }
}
```
